# Generated by Django 5.1.5 on 2025-08-06 16:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typingApp', '0002_blogpost_alter_jobpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
